/* eslint-disable no-unused-vars */
const appName = 'Dlicom';

export default {
  welcome: 'Welcome To Dlicom',
  welcomeNote: 'Create your own wallet ',
  createNewWallet: 'Create Wallet',
  importWallet: 'Import Wallet',
  securityScreen: 'Security screen',
  forgotPwd: 'Forgot password?',
  back: 'Back',
  chooseYourUserName: 'Choose your username',
  walletNote: 'You can choose your random name',
  next: 'Next',
  back_up_your_sed_phrase: 'Back up your seed phrase',
  back_up_your_sed_phrase_note:
    'Your secret recovery phrase is used to recover your crypto if you lose your phone or switch to a different wallet\n\n\nSave these 12 word in secure location,such as a password manger.',
  copy_seed_phrase: 'Copy seed phrase',
  backup_on_cloud: 'Backup on cloud',
  backup_manually: 'Backup manually',
  enter_your_keys: 'Enter your keys',
  paste_your_keys_here: 'Paste your keys here ',
  confirm: 'Confirm',
  cancel: 'Cancel',
  seed_phrase: 'Seed Phrase',
  confirm_seed_phrase: 'Confirm Seed Phrase',
  confirm_seed_phrase_note:
    'Verify yor saved your secret recovery phrase by select 3 correct word',
  chose_coin: 'Chose Coin',
  coins: 'Coins',
  chat: 'Chats',
  status: 'Status',
  share_chat: 'Share chat',
  mark_all_read: 'Mark all read',
  clear_history: 'Clear history',
  delete_chat: 'Delete chat',
  settings: 'Settings',
  profile: 'Profile',
  dark_white: 'Dark/White',
  privacy_and_security: 'Privacy and security',
  privacy: 'Privacy',
  notifications: 'Notifications',
  notification_preferences: 'Notification Preferences',
  backup_seed_phrase: 'Backup Seed Phrase',
  reset_face_id: 'Reset Face Id',
  security: 'Security',
  preview_message: 'Preview Message',
  display_read_message: 'Display read message',
  preview_channel_link: 'Preview Channel link',
  who_can_chat_with_me: 'Who can chat with me',
  who_can_see_my_profile_picture: 'Who can see my profile picture',
  show_notification: 'Show notification',
  notification_from_non_contact: 'Notification from non contact',
  show_mentions: 'Show @ mentions',
  wallet_transaction: 'Wallet transaction',
  send: 'Send',
  receive: 'Receive',
  scan: 'Scan',
  tokens: 'Tokens',
  swap: 'Swap',
  authenticationPromptTitle: 'Please authenticate in order to use Dlicom',
  createPassword: 'Create Password',
  addNewWallet: 'Add New Wallet',
  unlockWallet: 'Unlock Wallet',
  verifyPassword: 'Verify Password',
  wallet_address: 'Wallet Address',
  name: 'Name',
  symbol: 'Symbol',
  decimals: 'Decimal',
  save: 'Save',
  custom_network: 'Custom Network',
  history: 'History',
  wallet_history: 'Wallet History',
};
